In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
dataset=pd.read_csv('final_dataset_merged.csv')
dataset.head(5)

Unnamed: 0  Flow Duration  Flow Bytes/s  Flow Packets/s  Total Fwd Packets  \
0         0.0            1.0  2.944000e+09       2000000.0                2.0   
1         1.0            1.0  2.944000e+09       2000000.0                2.0   
2         2.0            1.0  2.944000e+09       2000000.0                2.0   
3         3.0            1.0  2.944000e+09       2000000.0                2.0   
4         4.0            1.0  2.944000e+09       2000000.0                2.0   

   Total Backward Packets  Total Length of Fwd Packets  \
0                     0.0                       2944.0   
1                     0.0                       2944.0   
2                     0.0                       2944.0   
3                     0.0                       2944.0   
4                     0.0                       2944.0   

   Total Length of Bwd Packets  Fwd Packet Length Mean  \
0                          0.0                  1472.0   
1                          0.0                  1472.0   
2                          0.0                  1472.0   
3                          0.0                  1472.0   
4                          0.0                  1472.0   

   Bwd Packet Length Mean  Max Packet Length  Min Packet Length  \
0                     0.0             1472.0             1472.0   
1                     0.0             1472.0             1472.0   
2                     0.0             1472.0             1472.0   
3                     0.0             1472.0             1472.0   
4                     0.0             1472.0             1472.0   

   Packet Length Std  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  \
0                0.0            1.0           0.0           1.0           1.0   
1                0.0            1.0           0.0           1.0           1.0   
2                0.0            1.0           0.0           1.0           1.0   
3                0.0            1.0           0.0           1.0           1.0   
4                0.0            1.0           0.0           1.0           1.0   

   SYN Flag Count  ACK Flag Count  RST Flag Count  PSH Flag Count  \
0             0.0             0.0             0.0             0.0   
1             0.0             0.0             0.0             0.0   
2             0.0             0.0             0.0             0.0   
3             0.0             0.0             0.0             0.0   
4             0.0             0.0             0.0             0.0   

   FIN Flag Count  URG Flag Count  Subflow Fwd Packets  Subflow Bwd Packets  \
0             0.0             0.0                  2.0                  0.0   
1             0.0             0.0                  2.0                  0.0   
2             0.0             0.0                  2.0                  0.0   
3             0.0             0.0                  2.0                  0.0   
4             0.0             0.0                  2.0                  0.0   

   Subflow Fwd Bytes  Subflow Bwd Bytes  Init_Win_bytes_forward  \
0             2944.0                0.0                    -1.0   
1             2944.0                0.0                    -1.0   
2             2944.0                0.0                    -1.0   
3             2944.0                0.0                    -1.0   
4             2944.0                0.0                    -1.0   

   Init_Win_bytes_backward  Active Mean  Active Std  Idle Mean  Idle Std  \
0                     -1.0          0.0         0.0        0.0       0.0   
1                     -1.0          0.0         0.0        0.0       0.0   
2                     -1.0          0.0         0.0        0.0       0.0   
3                     -1.0          0.0         0.0        0.0       0.0   
4                     -1.0          0.0         0.0        0.0       0.0   

       Label  
0  DrDoS_DNS  
1  DrDoS_DNS  
2  DrDoS_DNS  
3  DrDoS_DNS  
4  DrDoS_DNS

In [4]:
sorted(dataset['Label'].unique())

['BENIGN',
 'DrDoS_DNS',
 'DrDoS_LDAP',
 'DrDoS_MSSQL',
 'DrDoS_NTP',
 'DrDoS_NetBIOS',
 'DrDoS_SNMP',
 'DrDoS_SSDP']

In [5]:
x=max(dataset['Flow Bytes/s'])
print(x)
inf_rows = dataset[np.isinf(dataset['Flow Bytes/s'])]
inf_rows

inf


Unnamed: 0  Flow Duration  Flow Bytes/s  Flow Packets/s  \
73             73.0            0.0           inf             inf   
83             83.0            0.0           inf             inf   
111           111.0            0.0           inf             inf   
117           117.0            0.0           inf             inf   
129           129.0            0.0           inf             inf   
...             ...            ...           ...             ...   
1399490   1399490.0            0.0           inf             inf   
1399557   1399557.0            0.0           inf             inf   
1399738   1399738.0            0.0           inf             inf   
1399826   1399826.0            0.0           inf             inf   
1399881   1399881.0            0.0           inf             inf   

         Total Fwd Packets  Total Backward Packets  \
73                     2.0                     0.0   
83                     2.0                     0.0   
111                    2.0                     0.0   
117                    2.0                     0.0   
129                    2.0                     0.0   
...                    ...                     ...   
1399490                2.0                     0.0   
1399557                2.0                     0.0   
1399738                2.0                     0.0   
1399826                2.0                     0.0   
1399881                2.0                     0.0   

         Total Length of Fwd Packets  Total Length of Bwd Packets  \
73                            2944.0                          0.0   
83                            2944.0                          0.0   
111                           2944.0                          0.0   
117                           2944.0                          0.0   
129                           2944.0                          0.0   
...                              ...                          ...   
1399490                        738.0                          0.0   
1399557                        802.0                          0.0   
1399738                        766.0                          0.0   
1399826                        802.0                          0.0   
1399881                        766.0                          0.0   

         Fwd Packet Length Mean  Bwd Packet Length Mean  Max Packet Length  \
73                       1472.0                     0.0             1472.0   
83                       1472.0                     0.0             1472.0   
111                      1472.0                     0.0             1472.0   
117                      1472.0                     0.0             1472.0   
129                      1472.0                     0.0             1472.0   
...                         ...                     ...                ...   
1399490                   369.0                     0.0              369.0   
1399557                   401.0                     0.0              401.0   
1399738                   383.0                     0.0              383.0   
1399826                   401.0                     0.0              401.0   
1399881                   383.0                     0.0              383.0   

         Min Packet Length  Packet Length Std  Flow IAT Mean  Flow IAT Std  \
73                  1472.0                0.0            0.0           0.0   
83                  1472.0                0.0            0.0           0.0   
111                 1472.0                0.0            0.0           0.0   
117                 1472.0                0.0            0.0           0.0   
129                 1472.0                0.0            0.0           0.0   
...                    ...                ...            ...           ...   
1399490              369.0                0.0            0.0           0.0   
1399557              401.0                0.0            0.0           0.0   
1399738              383.0                0.0            0.0           0.0 

In [6]:
max_value = dataset['Flow Bytes/s'][~np.isinf(dataset['Flow Bytes/s'])].max()
min_value = dataset['Flow Bytes/s'][~np.isinf(dataset['Flow Bytes/s'])].min()

dataset['Flow Bytes/s'].replace(np.inf, max_value, inplace=True)
dataset['Flow Bytes/s'].replace(-np.inf, min_value, inplace=True)

# Convert column to float
dataset['Flow Bytes/s'] = dataset['Flow Bytes/s'].astype(float)

C:\Users\meera\AppData\Local\Temp\ipykernel_4296\1460234748.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Flow Bytes/s'].replace(np.inf, max_value, inplace=True)
C:\Users\meera\AppData\Local\Temp\ipykernel_4296\1460234748.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a 

In [7]:
max_value = dataset['Flow Packets/s'][~np.isinf(dataset['Flow Packets/s'])].max()
min_value = dataset['Flow Packets/s'][~np.isinf(dataset['Flow Packets/s'])].min()

dataset['Flow Packets/s'].replace(np.inf, max_value, inplace=True)
dataset['Flow Packets/s'].replace(-np.inf, min_value, inplace=True)

# Convert to float
dataset['Flow Packets/s'] = dataset['Flow Packets/s'].astype(float)


C:\Users\meera\AppData\Local\Temp\ipykernel_4296\356924476.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Flow Packets/s'].replace(np.inf, max_value, inplace=True)
C:\Users\meera\AppData\Local\Temp\ipykernel_4296\356924476.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a 

In [8]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1600000 entries, 0 to 1599999
Data columns (total 34 columns):
 #   Column                       Non-Null Count    Dtype  
---  ------                       --------------    -----  
 0   Unnamed: 0                   1400000 non-null  float64
 1   Flow Duration                1600000 non-null  float64
 2   Flow Bytes/s                 1600000 non-null  float64
 3   Flow Packets/s               1600000 non-null  float64
 4   Total Fwd Packets            1600000 non-null  float64
 5   Total Backward Packets       1600000 non-null  float64
 6   Total Length of Fwd Packets  1600000 non-null  float64
 7   Total Length of Bwd Packets  1600000 non-null  float64
 8   Fwd Packet Length Mean       1600000 non-null  float64
 9   Bwd Packet Length Mean       1600000 non-null  float64
 10  Max Packet Length            1600000 non-null  float64
 11  Min Packet Length            1600000 non-null  float64
 12  Packet Length Std            1600000 non-n

In [9]:
dataset.isnull().sum()

Unnamed: 0                     200000
Flow Duration                       0
Flow Bytes/s                        0
Flow Packets/s                      0
Total Fwd Packets                   0
Total Backward Packets              0
Total Length of Fwd Packets         0
Total Length of Bwd Packets         0
Fwd Packet Length Mean              0
Bwd Packet Length Mean              0
Max Packet Length                   0
Min Packet Length                   0
Packet Length Std                   0
Flow IAT Mean                       0
Flow IAT Std                        0
Flow IAT Max                        0
Flow IAT Min                        0
SYN Flag Count                      0
ACK Flag Count                      0
RST Flag Count                      0
PSH Flag Count                      0
FIN Flag Count                      0
URG Flag Count                      0
Subflow Fwd Packets                 0
Subflow Bwd Packets                 0
Subflow Fwd Bytes                   0
Subflow Bwd 

In [10]:
dataset.drop('Unnamed: 0',axis=1,inplace=True)

In [11]:
dataset.describe()

Flow Duration  Flow Bytes/s  Flow Packets/s  Total Fwd Packets  \
count   1.600000e+06  1.600000e+06    1.600000e+06       1.600000e+06   
mean    1.057302e+06  1.009690e+09    1.145621e+06       1.184328e+01   
std     9.713214e+06  1.094284e+09    9.522790e+05       3.380822e+02   
min     0.000000e+00  0.000000e+00    3.669343e-02       1.000000e+00   
25%     1.000000e+00  1.180724e+07    4.081633e+04       2.000000e+00   
50%     2.000000e+00  5.700000e+08    1.000000e+06       2.000000e+00   
75%     8.530000e+02  1.472000e+09    2.000000e+06       3.562633e+00   
max     1.199959e+08  2.944000e+09    4.000000e+06       9.984600e+04   

       Total Backward Packets  Total Length of Fwd Packets  \
count            1.600000e+06                 1.600000e+06   
mean             8.628107e-01                 5.305538e+03   
std              1.760649e+01                 4.005404e+04   
min              0.000000e+00                 0.000000e+00   
25%              0.000000e+00                 8.320000e+02   
50%              0.000000e+00                 2.741823e+03   
75%              0.000000e+00                 2.944000e+03   
max              4.602000e+03                 1.526642e+07   

       Total Length of Bwd Packets  Fwd Packet Length Mean  \
count                 1.600000e+06            1.600000e+06   
mean                  1.155657e+03            7.360633e+02   
std                   5.454868e+04            5.687081e+02   
min                   0.000000e+00            0.000000e+00   
25%                   0.000000e+00            2.470000e+02   
50%                   0.000000e+00            4.400000e+02   
75%                   0.000000e+00            1.472000e+03   
max                   1.099376e+07            3.015291e+03   

       Bwd Packet Length Mean  Max Packet Length  Min Packet Length  \
count            1.600000e+06       1.600000e+06       1.600000e+06   
mean             1.372905e+01       7.816517e+02       7.217719e+02   
std              9.912331e+01       7.189013e+02       5.802331e+02   
min              0.000000e+00       0.000000e+00       0.000000e+00   
25%              0.000000e+00       3.690000e+02       2.290000e+02   
50%              0.000000e+00       4.400000e+02       4.400000e+02   
75%              0.000000e+00       1.472000e+03       1.472000e+03   
max              5.011060e+03       3.796000e+04       1.472000e+03   

       Packet Length Std  Flow IAT Mean  Flow IAT Std  Flow IAT Max  \
count       1.600000e+06   1.600000e+06  1.600000e+06  1.600000e+06   
mean        1.731575e+01   4.504706e+04  1.120296e+05  4.529721e+05   
std         9.676336e+01   4.018914e+05  1.010950e+06  4.363816e+06   
min         0.000000e+00   0.000000e+00  0.000000e+00  0.000000e+00   
25%         0.000000e+00   1.000000e+00  0.000000e+00  1.000000e+00   
50%         0.000000e+00   2.000000e+00  0.000000e+00  2.000000e+00   
75%         0.000000e+00   4.900000e+01  4.176528e+01  1.950000e+02   
max         6.616562e+03   4.300800e+07  6.293758e+07  1.199480e+08   

       Flow IAT Min  SYN Flag Count  ACK Flag Count  RST Flag Count  \
count  1.600000e+06    1.600000e+06    1.600000e+06    1.600000e+06   
mean   1.951587e+03    5.708334e-04    2.210926e-02    1.657853e-02   
std    8.810722e+04    2.328684e-02    1.469038e-01    1.275460e-01   
min    0.000000e+00    0.000000e+00    0.000000e+00    0.000000e+00   
25%    1.000000e+00    0.000000e+00    0.000000e+00    0.000000e+00   
50%    1.000000e+00    0.000000e+00    0.000000e+00    0.000000e+00   
75%    2.000000e+00    0.000000e+00    0.000000e+00    0.000000e+00   
max    4.300800e+07    1.000000e+00    1.000000e+00    1.000000e+00   

       PSH Flag Count  FIN Flag Count  URG Flag Count  Subflow Fwd Packets  \
count    1.600000e+06    1.600000e+06    1.600000e+06         1.600000e+06   
mean     9.682194e-06    1.004314e-05    5.485071e-02         1.178331e+01   
std      3.903824e-05    4.485060e-05    2.275122e-01         3.381344e+02   

In [12]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
dataset['Label']=le.fit_transform(dataset['Label'])

In [13]:
sorted(dataset['Label'].unique())

[0, 1, 2, 3, 4, 5, 6, 7]

data spliting

In [14]:
x=dataset.drop('Label',axis=1)

In [15]:
y=dataset['Label']

In [16]:
y

0          1
1          1
2          1
3          1
4          1
          ..
1599995    0
1599996    0
1599997    0
1599998    0
1599999    0
Name: Label, Length: 1600000, dtype: int32

In [17]:
from sklearn.model_selection import train_test_split 

In [18]:
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [19]:
len(X_train)

1280000

In [20]:
X_train.isnull().sum()

Flow Duration                  0
Flow Bytes/s                   0
Flow Packets/s                 0
Total Fwd Packets              0
Total Backward Packets         0
Total Length of Fwd Packets    0
Total Length of Bwd Packets    0
Fwd Packet Length Mean         0
Bwd Packet Length Mean         0
Max Packet Length              0
Min Packet Length              0
Packet Length Std              0
Flow IAT Mean                  0
Flow IAT Std                   0
Flow IAT Max                   0
Flow IAT Min                   0
SYN Flag Count                 0
ACK Flag Count                 0
RST Flag Count                 0
PSH Flag Count                 0
FIN Flag Count                 0
URG Flag Count                 0
Subflow Fwd Packets            0
Subflow Bwd Packets            0
Subflow Fwd Bytes              0
Subflow Bwd Bytes              0
Init_Win_bytes_forward         0
Init_Win_bytes_backward        0
Active Mean                    0
Active Std                     0
Idle Mean 

In [21]:
len(X_test)

320000

In [22]:
len(Y_train)

1280000

In [23]:
len(Y_test)

320000

In [24]:
np.isinf(X_train).sum()

Flow Duration                  0
Flow Bytes/s                   0
Flow Packets/s                 0
Total Fwd Packets              0
Total Backward Packets         0
Total Length of Fwd Packets    0
Total Length of Bwd Packets    0
Fwd Packet Length Mean         0
Bwd Packet Length Mean         0
Max Packet Length              0
Min Packet Length              0
Packet Length Std              0
Flow IAT Mean                  0
Flow IAT Std                   0
Flow IAT Max                   0
Flow IAT Min                   0
SYN Flag Count                 0
ACK Flag Count                 0
RST Flag Count                 0
PSH Flag Count                 0
FIN Flag Count                 0
URG Flag Count                 0
Subflow Fwd Packets            0
Subflow Bwd Packets            0
Subflow Fwd Bytes              0
Subflow Bwd Bytes              0
Init_Win_bytes_forward         0
Init_Win_bytes_backward        0
Active Mean                    0
Active Std                     0
Idle Mean 

In [25]:
np.isinf(X_test).sum()

Flow Duration                  0
Flow Bytes/s                   0
Flow Packets/s                 0
Total Fwd Packets              0
Total Backward Packets         0
Total Length of Fwd Packets    0
Total Length of Bwd Packets    0
Fwd Packet Length Mean         0
Bwd Packet Length Mean         0
Max Packet Length              0
Min Packet Length              0
Packet Length Std              0
Flow IAT Mean                  0
Flow IAT Std                   0
Flow IAT Max                   0
Flow IAT Min                   0
SYN Flag Count                 0
ACK Flag Count                 0
RST Flag Count                 0
PSH Flag Count                 0
FIN Flag Count                 0
URG Flag Count                 0
Subflow Fwd Packets            0
Subflow Bwd Packets            0
Subflow Fwd Bytes              0
Subflow Bwd Bytes              0
Init_Win_bytes_forward         0
Init_Win_bytes_backward        0
Active Mean                    0
Active Std                     0
Idle Mean 

Model building(Logistic regression)

In [26]:
from sklearn.linear_model import LogisticRegression

In [27]:
Model=LogisticRegression()

In [28]:
Model.fit(X_train,Y_train)

C:\Users\meera\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [29]:
y_pred=Model.predict(X_test)

In [30]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [31]:
accuracy = accuracy_score(Y_test, y_pred)
print(f"Model Accuracy: {accuracy:.2f}")

Model Accuracy: 0.47


In [32]:
cm = confusion_matrix(Y_test, y_pred)
print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[34852     0     0    50     0  5591     0     0]
 [   93     0 35356  2679    10  1584     0     0]
 [    2     0 38723   846     0     3     0     0]
 [   34     0  2464 37494     0     5     0     0]
 [ 5770     0     0 27969  2131  2085     0  1727]
 [   30     0    31  1728     0 38325     0     0]
 [   15     0 38168   156     0  1809     0     0]
 [19096     0   682  7869     0 12603     0    20]]


In [33]:
from sklearn.metrics import classification_report

report = classification_report(Y_test, y_pred)
print(report)


C:\Users\meera\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\meera\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


              precision    recall  f1-score   support

           0       0.58      0.86      0.69     40493
           1       0.00      0.00      0.00     39722
           2       0.34      0.98      0.50     39574
           3       0.48      0.94      0.63     39997
           4       1.00      0.05      0.10     39682
           5       0.62      0.96      0.75     40114
           6       0.00      0.00      0.00     40148
           7       0.01      0.00      0.00     40270

    accuracy                           0.47    320000
   macro avg       0.38      0.47      0.33    320000
weighted avg       0.38      0.47      0.34    320000



C:\Users\meera\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [34]:
import numpy as np
from sklearn.metrics import confusion_matrix

# Compute confusion matrix
cm = confusion_matrix(Y_test, y_pred)
num_classes = cm.shape[0]  # Number of classes

# Initialize lists
TP = np.diag(cm)  # True Positives (diagonal values)
FP = np.sum(cm, axis=0) - TP  # Column sum minus TP
FN = np.sum(cm, axis=1) - TP  # Row sum minus TP
TN = np.sum(cm) - (TP + FP + FN)  # Everything else

# Print per-class metrics
for i in range(num_classes):
    print(f"Class {i}:")
    print(f"  True Positives (TP): {TP[i]}")
    print(f"  False Positives (FP): {FP[i]}")
    print(f"  False Negatives (FN): {FN[i]}")
    print(f"  True Negatives (TN): {TN[i]}")
    print("-" * 30)


Class 0:
  True Positives (TP): 34852
  False Positives (FP): 25040
  False Negatives (FN): 5641
  True Negatives (TN): 254467
------------------------------
Class 1:
  True Positives (TP): 0
  False Positives (FP): 0
  False Negatives (FN): 39722
  True Negatives (TN): 280278
------------------------------
Class 2:
  True Positives (TP): 38723
  False Positives (FP): 76701
  False Negatives (FN): 851
  True Negatives (TN): 203725
------------------------------
Class 3:
  True Positives (TP): 37494
  False Positives (FP): 41297
  False Negatives (FN): 2503
  True Negatives (TN): 238706
------------------------------
Class 4:
  True Positives (TP): 2131
  False Positives (FP): 10
  False Negatives (FN): 37551
  True Negatives (TN): 280308
------------------------------
Class 5:
  True Positives (TP): 38325
  False Positives (FP): 23680
  False Negatives (FN): 1789
  True Negatives (TN): 256206
------------------------------
Class 6:
  True Positives (TP): 0
  False Positives (FP): 0
  F

Decision tree model building

In [35]:
from sklearn.tree import DecisionTreeClassifier

In [36]:
clf=DecisionTreeClassifier(criterion='gini',max_depth=8,random_state=42)

In [37]:
clf.fit(X_train,Y_train)

DecisionTreeClassifier(max_depth=8, random_state=42)

In [38]:
y_pred_tree = clf.predict(X_test)

In [39]:
accuracy = accuracy_score(Y_test, y_pred_tree)
print(f"Model Accuracy: {accuracy:.2f}")

Model Accuracy: 0.83


In [40]:
report_tree = classification_report(Y_test, y_pred_tree)
print(report_tree)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     40493
           1       0.77      0.26      0.39     39722
           2       0.50      0.64      0.56     39574
           3       0.92      0.95      0.93     39997
           4       0.99      1.00      1.00     39682
           5       0.95      0.99      0.97     40114
           6       0.64      0.85      0.73     40148
           7       0.99      0.96      0.97     40270

    accuracy                           0.83    320000
   macro avg       0.84      0.83      0.82    320000
weighted avg       0.85      0.83      0.82    320000



In [41]:
import xgboost as xgb

In [42]:
# Initialize the XGBoost classifier for multiclass classification
xgb_model = xgb.XGBClassifier(objective='multi:softmax', num_class=8, eval_metric='mlogloss', use_label_encoder=False)

# Train the model
xgb_model.fit(X_train, Y_train)


C:\Users\meera\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\core.py:158: UserWarning: [13:45:34] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0c55ff5f71b100e98-1\xgboost\xgboost-ci-windows\src\learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_class=8, num_parallel_tree=None, ...)

In [43]:
# Predict on test data
y_pred = xgb_model.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(Y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")


Accuracy: 83.53%


In [51]:
from sklearn.metrics import accuracy_score

# Assuming you already have your trained model and training data
y_train_pred = xgb_model.predict(X_train)  # Predict on training data
train_accuracy = accuracy_score(Y_train, y_train_pred)

print(f"Training Accuracy: {train_accuracy:.4f}")


Training Accuracy: 0.8349


In [44]:
# Save the model
xgb_model.save_model("xgboost_model.json")  # You can also use .bin


In [45]:
import numpy as np
from sklearn.metrics import confusion_matrix

# Compute confusion matrix
cm = confusion_matrix(Y_test, y_pred)
num_classes = cm.shape[0]  # Number of classes

# Initialize lists
TP = np.diag(cm)  # True Positives (diagonal values)
FP = np.sum(cm, axis=0) - TP  # Column sum minus TP
FN = np.sum(cm, axis=1) - TP  # Row sum minus TP
TN = np.sum(cm) - (TP + FP + FN)  # Everything else

# Print per-class metrics
for i in range(num_classes):
    print(f"Class {i}:")
    print(f"  True Positives (TP): {TP[i]}")
    print(f"  False Positives (FP): {FP[i]}")
    print(f"  False Negatives (FN): {FN[i]}")
    print(f"  True Negatives (TN): {TN[i]}")
    print("-" * 30)


Class 0:
  True Positives (TP): 40487
  False Positives (FP): 21
  False Negatives (FN): 6
  True Negatives (TN): 279486
------------------------------
Class 1:
  True Positives (TP): 10907
  False Positives (FP): 3435
  False Negatives (FN): 28815
  True Negatives (TN): 276843
------------------------------
Class 2:
  True Positives (TP): 26350
  False Positives (FP): 26295
  False Negatives (FN): 13224
  True Negatives (TN): 254131
------------------------------
Class 3:
  True Positives (TP): 38156
  False Positives (FP): 3398
  False Negatives (FN): 1841
  True Negatives (TN): 276605
------------------------------
Class 4:
  True Positives (TP): 39635
  False Positives (FP): 338
  False Negatives (FN): 47
  True Negatives (TN): 279980
------------------------------
Class 5:
  True Positives (TP): 39462
  False Positives (FP): 2057
  False Negatives (FN): 652
  True Negatives (TN): 277829
------------------------------
Class 6:
  True Positives (TP): 33649
  False Positives (FP): 16

In [46]:
import numpy as np
from sklearn.metrics import confusion_matrix

# Define class names (example)
class_names = ['BENIGN',
 'DrDoS_DNS',
 'DrDoS_LDAP',
 'DrDoS_MSSQL',
 'DrDoS_NTP',
 'DrDoS_NetBIOS',
 'DrDoS_SNMP',
 'DrDoS_SSDP']  # Update as needed

# Compute confusion matrix
cm = confusion_matrix(Y_test, y_pred, labels=range(len(class_names)))
num_classes = cm.shape[0]  # Number of classes

# Initialize metrics
TP = np.diag(cm)  # True Positives
FP = np.sum(cm, axis=0) - TP  # False Positives
FN = np.sum(cm, axis=1) - TP  # False Negatives
TN = np.sum(cm) - (TP + FP + FN)  # True Negatives

# Print per-class metrics
for i in range(num_classes):
    print(f"Class '{class_names[i]}':")
    print(f"  True Positives (TP): {TP[i]}")
    print(f"  False Positives (FP): {FP[i]}")
    print(f"  False Negatives (FN): {FN[i]}")
    print(f"  True Negatives (TN): {TN[i]}")
    print("-" * 40)


Class 'BENIGN':
  True Positives (TP): 40487
  False Positives (FP): 21
  False Negatives (FN): 6
  True Negatives (TN): 279486
----------------------------------------
Class 'DrDoS_DNS':
  True Positives (TP): 10907
  False Positives (FP): 3435
  False Negatives (FN): 28815
  True Negatives (TN): 276843
----------------------------------------
Class 'DrDoS_LDAP':
  True Positives (TP): 26350
  False Positives (FP): 26295
  False Negatives (FN): 13224
  True Negatives (TN): 254131
----------------------------------------
Class 'DrDoS_MSSQL':
  True Positives (TP): 38156
  False Positives (FP): 3398
  False Negatives (FN): 1841
  True Negatives (TN): 276605
----------------------------------------
Class 'DrDoS_NTP':
  True Positives (TP): 39635
  False Positives (FP): 338
  False Negatives (FN): 47
  True Negatives (TN): 279980
----------------------------------------
Class 'DrDoS_NetBIOS':
  True Positives (TP): 39462
  False Positives (FP): 2057
  False Negatives (FN): 652
  True Nega

In [52]:
import numpy as np
from sklearn.metrics import confusion_matrix

# Define class names (example)
class_names = ['BENIGN',
 'DrDoS_DNS',
 'DrDoS_LDAP',
 'DrDoS_MSSQL',
 'DrDoS_NTP',
 'DrDoS_NetBIOS',
 'DrDoS_SNMP',
 'DrDoS_SSDP']  # Update as needed

# Compute confusion matrix
cm = confusion_matrix(Y_train, y_train_pred, labels=range(len(class_names)))
num_classes = cm.shape[0]  # Number of classes

# Initialize metrics
TP = np.diag(cm)  # True Positives
FP = np.sum(cm, axis=0) - TP  # False Positives
FN = np.sum(cm, axis=1) - TP  # False Negatives
TN = np.sum(cm) - (TP + FP + FN)  # True Negatives

# Print per-class metrics
for i in range(num_classes):
    print(f"Class '{class_names[i]}':")
    print(f"  True Positives (TP): {TP[i]}")
    print(f"  False Positives (FP): {FP[i]}")
    print(f"  False Negatives (FN): {FN[i]}")
    print(f"  True Negatives (TN): {TN[i]}")
    print("-" * 40)


Class 'BENIGN':
  True Positives (TP): 162380
  False Positives (FP): 42
  False Negatives (FN): 22
  True Negatives (TN): 1117556
----------------------------------------
Class 'DrDoS_DNS':
  True Positives (TP): 44008
  False Positives (FP): 13748
  False Negatives (FN): 116132
  True Negatives (TN): 1106112
----------------------------------------
Class 'DrDoS_LDAP':
  True Positives (TP): 106990
  False Positives (FP): 105821
  False Negatives (FN): 53280
  True Negatives (TN): 1013909
----------------------------------------
Class 'DrDoS_MSSQL':
  True Positives (TP): 152635
  False Positives (FP): 13638
  False Negatives (FN): 7293
  True Negatives (TN): 1106434
----------------------------------------
Class 'DrDoS_NTP':
  True Positives (TP): 157808
  False Positives (FP): 1309
  False Negatives (FN): 168
  True Negatives (TN): 1120715
----------------------------------------
Class 'DrDoS_NetBIOS':
  True Positives (TP): 157298
  False Positives (FP): 8094
  False Negatives (FN)